### ISSUE TITLE
Any way to mount the back panel using these parts?

### ISSUE THREAD

**Issue by bassamanator** [zruncho3d/ZeroPanels#1]
I'd like to mount my Voron 0.1 back panel using this design, but it seems this will only work for the size panels?

Interesting design. Thanks!

**Comment by zruncho3d** [comment]
(just seeing this now) 

You can lift the back panel up and it should still seal, at least using Tecnologic-style panels (a larger variant I really like).  More here:
https://github.com/zruncho3d/BoxZero

You may need to add some foam tape to the back, by the motors/umbilical plate though, but you shouldn't need a larger plate.
