### ISSUE TITLE
Insulation

### ISSUE THREAD

**Issue by taihon** [zruncho3d/ZeroPanels#2]
Hello. First of all - thank you for this mod :) It's fast to print and beatiful to look at.
In the FAQ section you've mentioned "clips enable the panels to float". How would i go about insulating v0 chamber then?

**Comment by taihon** [comment]
To anyone who comes here in the future - we're supposed to put foam tape on panels inbetween clips, as usual.

**Comment by zruncho3d** [comment]
Yep
